<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #1E3A8A;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #1E3A8A;
            margin: 0;
        }
        .stats {
            width: 100%;
            margin-bottom: 30px;
        }
        .stats td {
            width: 50%;
            padding: 15px;
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            text-align: center;
        }
        .stats h3 {
            margin: 0 0 5px 0;
            font-size: 14px;
            color: #6b7280;
            text-transform: uppercase;
        }
        .stats p {
            margin: 0;
            font-size: 24px;
            font-weight: bold;
            color: #111827;
        }
        table.reviews {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        table.reviews th, table.reviews td {
            border: 1px solid #e5e7eb;
            padding: 8px;
            text-align: left;
        }
        table.reviews th {
            background-color: #f3f4f6;
            color: #374151;
        }
        .positive { color: #16A34A; font-weight: bold; }
        .negative { color: #DC2626; font-weight: bold; }
        .neutral { color: #CA8A04; font-weight: bold; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $report->title }}</h1>
        <p>{{ $report->description ?? 'Auto-generated sentiment analysis report.' }}</p>
        <p><small>Generated on {{ now()->format('F j, Y, g:i a') }}</small></p>
    </div>

    <table class="stats">
        <tr>
            <td>
                <h3>Total Analyzed Reviews</h3>
                <p>{{ number_format($totalReviews) }}</p>
            </td>
            <td>
                <h3>Average Sentiment Score</h3>
                <p class="{{ $avgSentiment > 0 ? 'positive' : ($avgSentiment < 0 ? 'negative' : 'neutral') }}">
                    {{ $avgSentiment }}
                </p>
            </td>
        </tr>
    </table>

    <h2>Recent Feedback Sample</h2>
    <table class="reviews">
        <thead>
            <tr>
                <th width="15%">App</th>
                <th width="50%">Content</th>
                <th width="15%">Sentiment</th>
                <th width="20%">Topic / Intent</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reviews as $review)
                <tr>
                    <td>{{ $review->dataset->fintechApp->name ?? 'Unknown' }}</td>
                    <td>{{ Str::limit($review->cleaned_content ?? $review->content, 150) }}</td>
                    <td class="{{ strtolower($review->sentiment_label) }}">
                        {{ ucfirst($review->sentiment_label) }} <br>
                        <small>({{ $review->sentiment_compound }})</small>
                    </td>
                    <td>
                        {{ $review->topic ?? 'N/A' }} <br>
                        <small>{{ $review->intent ?? 'N/A' }}</small>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by FinPulse &copy; {{ date('Y') }}
    </div>
</body>
</html>
